LABEL_EXPLANATIONS = {
    "30C": "30도에서 세탁하세요.",
    "40C": "40도에서 세탁하세요.",
    "50C": "50도에서 세탁하세요.",
    "60C": "60도에서 세탁하세요.",
    "70C": "70도에서 세탁하세요.",
    "95C": "95도에서 세탁하세요.",

    "DN_bleach": "표백하지 마세요.",
    "DN_dry": "건조하지 마세요.",
    "DN_dry_clean": "드라이클리닝하지 마세요.",
    "DN_iron": "다림질하지 마세요.",
    "DN_steam": "스팀 다림질하지 마세요.",
    "DN_tumble_dry": "기계 건조하지 마세요.",
    "DN_wash": "세탁하지 마세요.",
    "DN_wring": "짜지 마세요.",

    "bleach": "표백 가능합니다.",
    "chlorine_bleach": "염소계 표백제를 사용하세요.",
    "non_chlorine_bleach": "산소계 표백제만 사용하세요.",

    "machine_wash_normal": "일반 코스로 세탁하세요.",
    "machine_wash_delicate": "섬세한 코스로 세탁하세요.",
    "hand_wash": "손세탁하세요.",

    # 누락된 라벨은 기본 설명 추가 (Null 방지)
    "dry_clean": "드라이클리닝 하세요.",
    "dry_clean_any_solvent": "모든 용제를 사용한 드라이클리닝 가능.",
    "dry_clean_low_heat": "드라이클리닝 시 저온으로 설정하세요.",
    "dry_clean_no_steam": "드라이클리닝 시 스팀 사용 금지.",
    "dry_flat": "평평한 곳에 건조하세요.",
    "line_dry": "옷걸이에 걸어 건조하세요.",
    "line_dry_in_shade": "그늘에서 옷걸이에 걸어 건조하세요.",
    "iron_high": "높은 온도로 다림질하세요.",
    "iron_low": "낮은 온도로 다림질하세요.",
    "iron_medium": "중간 온도로 다림질하세요.",
    "tumble_dry_low": "낮은 온도로 기계 건조하세요.",
    "tumble_dry_medium": "중간 온도로 기계 건조하세요.",
    "tumble_dry_normal": "보통 온도로 기계 건조하세요.",
    "tumble_dry_no_heat": "열 없이 기계 건조하세요.",
    "natural_dry": "자연 건조하세요.",
    "shade_dry": "그늘에서 건조하세요.",
    "wet_clean": "전문 습식 세탁 하세요.",
    "wring": "옷을 짜세요.",
    "Unknown Class": "알 수 없는 라벨입니다."
}
